const express = require('express')
require ('dotenv').config()
require('./config/database')
const cors = require('cors')
const router = require('./routes/index')
const app = express()

app.use(cors())
app.use(express.json())
app.use('/', router)
app.listen(4000, ()=>console.log('app listening on port 4000'))